services:
  shopee_seller:
    url: https://banhang.shopee.vn
    regex: 'sellerCenterFeVersion="(.*?)"'
  shopee_uat_seller:
    url: https://banhang.uat.shopee.vn/
    regex: 'sellerCenterFeVersion="(.*?)"'
  ghtk:
    url: https://docs.giaohangtietkiem.vn
    regex: 'v[0-9]+\.[0-9]+\.[0-9]'